name: Build and Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Test Build
        if: github.event_name == 'pull_request'
        run: bun run build

      - name: Build & Publish Electron App
        if: github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: bun run electron:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}