# .github/workflows/release.yml
name: Release
on:
  push:
    branches: [main]
jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        outputs:
            release_created: ${{ steps.release-please.outputs.release_created }}
            tag_name: ${{ steps.release-please.outputs.tag_name }}
        steps:
            - id: release-please
              uses: googleapis/release-please-action@v4
              with:
                  release-type: node
                  token: ${{ secrets.GITHUB_TOKEN }}

    build-and-upload:
        needs: release
        if: ${{ needs.release.outputs.release_created == 'true' }}
        uses: ./.github/workflows/build.yml
        secrets: inherit
        with:
          tag_name: ${{ needs.release.outputs.tag_name }}
